# DO NOT DELETE

src/config.c: include/config.h include/system.h
src/error.c: include/system.h
src/main.c: include/config.h include/system.h include/smime-gate.h
src/rwwrap.c: include/system.h
src/signal.c: include/system.h
src/smime-gate.c: include/config.h include/smtp.h include/smtp-types.h
src/smime-gate.c: include/system.h
src/smtp-lib.c: include/smtp-lib.h include/smtp-types.h include/system.h
src/smtp-types.c: include/smtp-types.h
src/smtp.c: include/smtp-lib.h include/smtp-types.h include/smtp.h
src/smtp.c: include/system.h
src/sysenv.c: include/system.h
src/wrapsock.c: include/system.h
src/wrapunix.c: include/system.h
